### ISSUE TITLE
ADSL E2E example needs touching up ahead of admiral 1.0

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/end_to_end_examples#31]
Example: switch out references to `admiral.test` for `pharmaversesdtm`, switch out references to deprecated `derive_vars_merged_dtm`.

**Comment by rossfarrugia** [comment]
@manciniedoardo we're in process of retiring this site, check out https://github.com/pharmaverse/examples from now instead and https://pharmaverse.github.io/examples/adam/ADSL.html. it uses quarto so easier to maintain and bring in new contributors

**Comment by manciniedoardo** [comment]
thanks @rossfarrugia
