### ISSUE TITLE
issue for issues

### ISSUE THREAD

**Issue by bms63** [pharmaverse/end_to_end_examples#7]
Hey all,

I'm pretty sure I put an issue in here and it is no longer visible - in either Open or Closed.

I think a few others disappeared as well?  @epijim @statasaurus

Did this repo get re-created???

**Comment by statasaurus** [comment]
No it didn't. I haven't seen any issues. Would you be able to put them in again?

**Comment by rossfarrugia** [comment]
closing - you might have been thinking about https://github.com/pharmaverse/pharmaverse/issues for the website main repo @bms63
